repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.13.0
    hooks:
      - id: validate_manifest

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort

  - repo: https://github.com/python/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
