name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        include:
          - python-version: 3.8
            os: windows-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
    - name: Test with tox
      run: |
        pip install tox
        tox -- --cov blacktex --cov-report xml --cov-report term
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.python-version == '3.9' }}
